from app.models import db, DailyLog, environment, SCHEMA
from sqlalchemy.sql import text
from datetime import datetime

def seed_daily_logs():
    daily_log1 = DailyLog(kid_id=1, title = 'Six-year-old Birthday Party', content ='ELsa invited all her kindergarten classmates to attend her birthday party. She had so much fun', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image1-Elsa-birthday-party.png', created_at=datetime(2024,6,6))
    daily_log2 = DailyLog(kid_id=1, title = 'First Day of Kindergarten', content ='First day of kindergarten! She is a elementary student now! ', image_url= 'https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image2-Elsa-first-day.png', created_at=datetime(2023,8,16))
    daily_log3 = DailyLog(kid_id=1, title = 'Running Near Carmel-by-the-sea', content ='chasing waves near the beautiful beach!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image3-elsa-chase-waves.png', created_at=datetime(2023,7,15))
    daily_log4 = DailyLog(kid_id=1, title = 'Ice-skating Progress ', content ='ELsa just unlock the skill of  backward crossover! ', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image4-elsa-iceskating.png', created_at=datetime(2023,5,20))
    daily_log5 = DailyLog(kid_id=2, title = 'Ballet Performance', content ='Well done with your first ballet performance, Anna!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image5-anna-ballet.png', created_at=datetime(2024,6,2))
    daily_log6 = DailyLog(kid_id=2, title = 'Raining Day', content ='jumping muddy puddles under the rain', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image6-anna-muddy-puddles.png', created_at=datetime(2024,3,18))
    daily_log7 = DailyLog(kid_id=2, title = 'Show Time', content ='Enjoying  disney on ice show!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image7-anna-watcing-show.png', created_at=datetime(2023,11,3))
    daily_log8 = DailyLog(kid_id=2, title = 'Park Fun', content ='Grilling marshmallows in the park ', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image8-anna-in-the-park.png', created_at=datetime(2023,10,6))
    daily_log9 = DailyLog(kid_id=3, title = 'Spending time with friends', content ='Play date with your best friend!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image9-Kristoff-playdate.png', created_at=datetime(2024,6,5))
    daily_log10 = DailyLog(kid_id=3, title = 'Soccer', content ='Kristoff is playing soccer!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image10-Kirstoff-play-soccer.png', created_at=datetime(2024,5,19))
    daily_log11 = DailyLog(kid_id=3, title = 'Running with Daddy', content ='Kristoff is running with Daddy', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image11-Kristoff-running-with-Dad.png', created_at=datetime(2024,3,21))
    daily_log12 = DailyLog(kid_id=3, title = 'Puppies', content ="Kristoff is patting our neighbor's puppies", image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image12-Kristoff-pat-puppies.png', created_at=datetime(2024,3,10))
    daily_log13 = DailyLog(kid_id=4, title = 'First Step', content ="Olaf's first step! This little one could walk now!", image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image13-Olaf-first-step.png', created_at=datetime(2024,6,9))
    daily_log14 = DailyLog(kid_id=4, title = 'Who is crawling now', content ='first crawling, go Olaf!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image14-Olaf-start-crawling.png', created_at=datetime(2024,2,7))
    daily_log15 = DailyLog(kid_id=4, title = 'Smile', content ="Olaf's first cute smile!", image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image15-Olaf-first-smail.png', created_at=datetime(2023,10,6))
    daily_log16 = DailyLog(kid_id=4, title = 'Birth', content ='Welcome to this beautiful world!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image16-Olaf-welcome.png', created_at=datetime(2023,9,9))
    daily_log17 = DailyLog(kid_id=5, title = 'Hiking', content ='Sofia loves hiking!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image17-Sofia-hiking.png', created_at=datetime(2024,8,2))
    daily_log18 = DailyLog(kid_id=5, title = 'Gardening Time', content ='Sofia is watering plants', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image18-Sofia-watering-plants.png', created_at=datetime(2024,7,25))
    daily_log19 = DailyLog(kid_id=5, title = 'Camping', content ='Amazing camping experience! Sofia enjoys it!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image19-Sofia-camping.png', created_at=datetime(2024,7,10))
    daily_log20 = DailyLog(kid_id=6, title = 'Cars always fun', content ='Jerry are playing with cars.', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image20-Jerry-playing-cars.png', created_at=datetime(2024,8,2))
    daily_log21 = DailyLog(kid_id=6, title = 'Bumble Bee Arrives', content ='Jerry dressed up as a bumble bee.', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image21-Jerry-bumble-bee.png', created_at=datetime(2023,10,31))
    daily_log22 = DailyLog(kid_id=6, title = 'Riding Tricycle', content ='Jerry rode tricycle in the neighborhood after dinner.', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image22-Jerry-riding-tricycle.png', created_at=datetime(2023,9,9))
    daily_log23 = DailyLog(kid_id=7, title = 'Playing With Toys', content ='Max loves to play with toys.', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image25-Max-play-toys.png', created_at=datetime(2023,6,12))
    daily_log24 = DailyLog(kid_id=7, title = 'Tummy Time', content ='Max could lift up his head during tummy time now', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image24-Max-tummy-time.png', created_at=datetime(2024,5,9))
    daily_log25 = DailyLog(kid_id=7, title = 'Max Was Born', content ='Hello, Max!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image23-Max-just-born.jpeg', created_at=datetime(2024,3,20))
    daily_log26 = DailyLog(kid_id=8, title = 'Petting Cats', content ='Maria spends her time with cats.', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image26-Maria-petting-cats.png', created_at=datetime(2024,8,3))
    daily_log27 = DailyLog(kid_id=8, title = 'Go, Girl', content ='Maria is having a good time in the playground!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image27-Maria-playing-slide.png', created_at=datetime(2024,7,30))
    daily_log28 = DailyLog(kid_id=8, title = 'Soccer', content ='Soccer is her favorite sport!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image28-Maria-playing-soccer.png', created_at=datetime(2024,6,30))
    daily_log29 = DailyLog(kid_id=9, title = 'School First Day', content ='Carlos is a little bit nervous to go to school.', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image29-Carlos-first-day.png', created_at=datetime(2024,8,5))
    daily_log30 = DailyLog(kid_id=9, title = 'Halloween ', content ='Trick or Treat? Carlos got a lot candies.', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image30-Carlos-trick-or-treat.png', created_at=datetime(2023,10,31))
    daily_log31 = DailyLog(kid_id=9, title = 'Soccer', content ='It is good to play soccer after school.', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image31-Carlos-playing-soccer.png', created_at=datetime(2023,10,25))
    daily_log32 = DailyLog(kid_id=10, title = 'Swing', content ='I can swing really high!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image32-Luis-playing-swing.png', created_at=datetime(2024,7,29))
    daily_log33 = DailyLog(kid_id=10, title = 'Soccer', content ='Luis really likes to play soccer!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image33-Luis-playing-soccer.png', created_at=datetime(2024,7,26))
    daily_log34 = DailyLog(kid_id=10, title = 'Sands Are My Friends', content ='Luis has played with sands for 1hour!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image34-Luis-playing-sands.png', created_at=datetime(2023,6,20))
    daily_log35 = DailyLog(kid_id=11, title = 'Lake', content ='Long loves the view near the lake', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image36-Long-playing-near-the-lake.png', created_at=datetime(2024,7,15))
    daily_log36 = DailyLog(kid_id=11, title = 'Taekwondo', content ='I am a little Taekwondo expert!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image37-Long-Taekwondo.png', created_at=datetime(2024,7,10))
    daily_log37 = DailyLog(kid_id=11, title = 'Painting', content ='Long is super excited to take the painting class!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image35-Long-painting.png', created_at=datetime(2024,7,2))
    daily_log38 = DailyLog(kid_id=12, title = 'Painting', content ='Look, there is a little artist!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image38-Mia-painting.png', created_at=datetime(2024,6,9))
    daily_log39 = DailyLog(kid_id=12, title = 'Chess', content ='Mia just started to learn how to play chess!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image39-Mia-chess.png', created_at=datetime(2024,6,5))
    daily_log40 = DailyLog(kid_id=12, title = 'Ballet', content ='Mia is such a pretty ballerina!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image40-Mia-ballet.png', created_at=datetime(2024,6,3))
    daily_log41 = DailyLog(kid_id=13, title = 'Piano', content ='Piano is her favorite toy!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image42-Emily-playing-piano.png', created_at=datetime(2024,8,4))
    daily_log42 = DailyLog(kid_id=13, title = 'Painting', content ='Emily likes to draw flowers and animals!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image41-Emily-painting.png', created_at=datetime(2024,7,5))
    daily_log43 = DailyLog(kid_id=13, title = 'Walk My Dog', content ='My dog is my best friend!', image_url='https://bundle-of-joy-july24.s3.us-west-1.amazonaws.com/capston-upload-images/daily-log-image43-Emily-playing-with-her-puppy.png', created_at=datetime(2024,7,4))

    daily_logs = [daily_log1, daily_log2, daily_log3, daily_log4, daily_log5, daily_log6,daily_log7,daily_log8,daily_log9,daily_log10,daily_log11,daily_log12,daily_log13,daily_log14,daily_log15,daily_log16,daily_log17,daily_log18,daily_log19,daily_log20,daily_log21,daily_log22,daily_log23,daily_log24,daily_log25,daily_log26,daily_log27,daily_log28,daily_log29,daily_log30,daily_log31,daily_log32,daily_log33,daily_log34,daily_log35,daily_log36,daily_log37,daily_log38,daily_log39,daily_log40,daily_log41,daily_log42,daily_log43]
    [db.session.add(log) for log in daily_logs]
    db.session.commit()

def undo_daily_logs():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.daily_logs RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM daily_logs"))
        
    db.session.commit()
